[package]
name = "nardi-hot-key"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { version = "0.2.98" }
evdev-rs = { version = "0.5.0", features = ["serde"] }
